#InvinciWolf Configuration File, Enjoy!!

#String(Text, Message) Values You Can Change.
#Change The Output If Player Inputs A Non-Number While Using The /getwolves Command.
NotNumb: That is not a number
#Change The Output If Player Inputs A Negative Value While Using The /getwolves Command.
NegValue: Cant Use Negative Values
#Change The Output If You Try To Use A Radius Higher Than You Are Allow To While Using The /getwolves Command.
TooFar: Too far away
#Change The Output If No Wolves Are Found While Using The /getwolves Command.
CantFind: No Wolves Found
#Change The Output If Player Doesnt Have Permissions To Use The /getwolves Command.
NoPerms:  You don't have permissions to use this
#Change The Output If Wolves Are Teleported While Using The /getwolves Command.
WolfTele: Wolves Teleported
#Change The Output If Player Attacks A Wolf While The Owner Is Offline.
OwnOffline: Wolf's Owner Is Offline Don't Kill Their Wolves


#Integer(Number) Values You Can Change.
#Change The Max Wolves A Regular Player Can Own.
Max_Wolves: 10
#Change The Max Radius Mods/Non-Ops(No Permissions) Can Use For The /getwolves Command.
Max_Admin_Tele_Radius: 128
#Change The Max Radius Admins/Ops(No Permissions) Can Use For The /getwolves Command.
Max_Tele_Radius: 64