name: InvinciWolf
main: net.D3GN.MiracleM4n.InvinciWolf.InvinciWolf
version: 1.7.2
website: 
author: MiracleM4n
description: Provides invincibility to wolves if owner is offline...and more.
commands:
    getwolves:
        description: Get all nearby wolves.
        usage: |
            /<command> [radius]
            Example: /<command> - See this info.
            Example: /<command> 30 - Get your wolves from a radius of 30.
            